kind = "web"
previewPath = "/"
title = "Vaulty"
version = "1.0.0"
id = "artifacts/vaulty"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22570

[services.development]
run = "PORT=22570 BASE_PATH=/ pnpm --filter @workspace/vaulty run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/vaulty", "run", "build" ]
publicDir = "artifacts/vaulty/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22570"
BASE_PATH = "/"
